[phases.setup]
nixPkgs = ['python39', 'postgresql']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT'

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT'
